# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Address:
    """A physical or virtual address, or a range of addresses, in an 'addressable region' (memory or a binary file)."""

    absolute_address : int = field(default=-1, metadata={"schema_property_name": "absoluteAddress"})
    fully_qualified_name : str = field(default=None, metadata={"schema_property_name": "fullyQualifiedName"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    kind : str = field(default=None, metadata={"schema_property_name": "kind"})
    length : int = field(default=None, metadata={"schema_property_name": "length"})
    name : str = field(default=None, metadata={"schema_property_name": "name"})
    offset_from_parent : int = field(default=None, metadata={"schema_property_name": "offsetFromParent"})
    parent_index : int = field(default=-1, metadata={"schema_property_name": "parentIndex"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    relative_address : int = field(default=None, metadata={"schema_property_name": "relativeAddress"})
