# This file was generated by jschema_to_python version 1.2.3.

from ._multiformat_message_string import MultiformatMessageString
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class ArtifactContent:
    """Represents the contents of an artifact."""

    binary : str = field(default=None, metadata={"schema_property_name": "binary"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    rendered : MultiformatMessageString = field(default=None, metadata={"schema_property_name": "rendered"})
    text : str = field(default=None, metadata={"schema_property_name": "text"})
