# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class ArtifactLocation:
    """Specifies the location of an artifact."""

    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    uri : str = field(default=None, metadata={"schema_property_name": "uri"})
    uri_base_id : str = field(default=None, metadata={"schema_property_name": "uriBaseId"})
