# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_location import ArtifactLocation
from ._property_bag import PropertyBag
from ._replacement import Replacement
from attrs import define
from attrs import field


@define()
class ArtifactChange:
    """A change to a single artifact."""

    artifact_location : ArtifactLocation = field(metadata={"schema_property_name": "artifactLocation"})
    replacements : list[Replacement] = field(metadata={"schema_property_name": "replacements"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
