# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_content import ArtifactContent
from ._artifact_location import ArtifactLocation
from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Artifact:
    """A single artifact. In some cases, this artifact might be nested within another artifact."""

    contents : ArtifactContent = field(default=None, metadata={"schema_property_name": "contents"})
    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    encoding : str = field(default=None, metadata={"schema_property_name": "encoding"})
    hashes : dict[str, str] = field(default=None, metadata={"schema_property_name": "hashes"})
    last_modified_time_utc : str = field(default=None, metadata={"schema_property_name": "lastModifiedTimeUtc"})
    length : int = field(default=-1, metadata={"schema_property_name": "length"})
    location : ArtifactLocation = field(default=None, metadata={"schema_property_name": "location"})
    mime_type : str = field(default=None, metadata={"schema_property_name": "mimeType"})
    offset : int = field(default=None, metadata={"schema_property_name": "offset"})
    parent_index : int = field(default=-1, metadata={"schema_property_name": "parentIndex"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    roles : list[str] = field(factory=list, metadata={"schema_property_name": "roles"})
    source_language : str = field(default=None, metadata={"schema_property_name": "sourceLanguage"})
