# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_location import ArtifactLocation
from ._message import Message
from ._property_bag import PropertyBag
from ._rectangle import Rectangle
from ._region import Region
from attrs import define
from attrs import field


@define()
class Attachment:
    """An artifact relevant to a result."""

    artifact_location : ArtifactLocation = field(metadata={"schema_property_name": "artifactLocation"})
    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    rectangles : list[Rectangle] = field(factory=list, metadata={"schema_property_name": "rectangles"})
    regions : list[Region] = field(factory=list, metadata={"schema_property_name": "regions"})
