# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._property_bag import PropertyBag
from ._thread_flow import ThreadFlow
from attrs import define
from attrs import field


@define()
class CodeFlow:
    """A set of threadFlows which together describe a pattern of code execution relevant to detecting a result."""

    thread_flows : list[ThreadFlow] = field(metadata={"schema_property_name": "threadFlows"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
