# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_location import ArtifactLocation
from ._invocation import Invocation
from ._property_bag import PropertyBag
from ._tool import Tool
from attrs import define
from attrs import field


@define()
class Conversion:
    """Describes how a converter transformed the output of a static analysis tool from the analysis tool's native output format into the SARIF format."""

    tool : Tool = field(metadata={"schema_property_name": "tool"})
    analysis_tool_log_files : list[ArtifactLocation] = field(factory=list, metadata={"schema_property_name": "analysisToolLogFiles"})
    invocation : Invocation = field(default=None, metadata={"schema_property_name": "invocation"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
