# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from ._reporting_configuration import ReportingConfiguration
from ._reporting_descriptor_reference import ReportingDescriptorReference
from attrs import define
from attrs import field


@define()
class ConfigurationOverride:
    """Information about how a specific rule or notification was reconfigured at runtime."""

    configuration : ReportingConfiguration = field(metadata={"schema_property_name": "configuration"})
    descriptor : ReportingDescriptorReference = field(metadata={"schema_property_name": "descriptor"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
