# This file was generated by jschema_to_python version 1.1.0.

import attr


@attr.s
class EdgeTraversal(object):
    """Represents the traversal of a single edge during a graph traversal."""

    edge_id = attr.ib()
    final_state = attr.ib(default=None)
    message = attr.ib(default=None)
    properties = attr.ib(default=None)
    step_over_edge_count = attr.ib(default=None)
