# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._multiformat_message_string import MultiformatMessageString
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class EdgeTraversal:
    """Represents the traversal of a single edge during a graph traversal."""

    edge_id : str = field(metadata={"schema_property_name": "edgeId"})
    final_state : dict[str, MultiformatMessageString] = field(default=None, metadata={"schema_property_name": "finalState"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    step_over_edge_count : int = field(default=None, metadata={"schema_property_name": "stepOverEdgeCount"})
