# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from ._stack import Stack
from attrs import define
from attrs import field


@define()
class Exception:
    """Describes a runtime exception encountered during the execution of an analysis tool."""

    inner_exceptions : list["Exception"] = field(factory=list, metadata={"schema_property_name": "innerExceptions"})
    kind : str = field(default=None, metadata={"schema_property_name": "kind"})
    message : str = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    stack : Stack = field(default=None, metadata={"schema_property_name": "stack"})
