# This file was generated by jschema_to_python version 1.1.0.

import attr


@attr.s
class Exception(object):
    """Describes a runtime exception encountered during the execution of an analysis tool."""

    inner_exceptions = attr.ib(default=None)
    kind = attr.ib(default=None)
    message = attr.ib(default=None)
    properties = attr.ib(default=None)
    stack = attr.ib(default=None)
