# This file was generated by jschema_to_python version 1.2.3.

from ._address import Address
from ._artifact import Artifact
from ._conversion import Conversion
from ._graph import Graph
from ._invocation import Invocation
from ._logical_location import LogicalLocation
from ._property_bag import PropertyBag
from ._result import Result
from ._thread_flow_location import ThreadFlowLocation
from ._tool_component import ToolComponent
from ._web_request import WebRequest
from ._web_response import WebResponse
from attrs import define
from attrs import field


@define()
class ExternalProperties:
    """The top-level element of an external property file."""

    addresses : list[Address] = field(factory=list, metadata={"schema_property_name": "addresses"})
    artifacts : list[Artifact] = field(factory=list, metadata={"schema_property_name": "artifacts"})
    conversion : Conversion = field(default=None, metadata={"schema_property_name": "conversion"})
    driver : ToolComponent = field(default=None, metadata={"schema_property_name": "driver"})
    extensions : list[ToolComponent] = field(factory=list, metadata={"schema_property_name": "extensions"})
    externalized_properties : PropertyBag = field(default=None, metadata={"schema_property_name": "externalizedProperties"})
    graphs : list[Graph] = field(factory=list, metadata={"schema_property_name": "graphs"})
    guid : str = field(default=None, metadata={"schema_property_name": "guid"})
    invocations : list[Invocation] = field(factory=list, metadata={"schema_property_name": "invocations"})
    logical_locations : list[LogicalLocation] = field(factory=list, metadata={"schema_property_name": "logicalLocations"})
    policies : list[ToolComponent] = field(factory=list, metadata={"schema_property_name": "policies"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    results : list[Result] = field(factory=list, metadata={"schema_property_name": "results"})
    run_guid : str = field(default=None, metadata={"schema_property_name": "runGuid"})
    schema : str = field(default=None, metadata={"schema_property_name": "schema"})
    taxonomies : list[ToolComponent] = field(factory=list, metadata={"schema_property_name": "taxonomies"})
    thread_flow_locations : list[ThreadFlowLocation] = field(factory=list, metadata={"schema_property_name": "threadFlowLocations"})
    translations : list[ToolComponent] = field(factory=list, metadata={"schema_property_name": "translations"})
    version : str = field(default=None, metadata={"schema_property_name": "version"})
    web_requests : list[WebRequest] = field(factory=list, metadata={"schema_property_name": "webRequests"})
    web_responses : list[WebResponse] = field(factory=list, metadata={"schema_property_name": "webResponses"})
