# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_change import ArtifactChange
from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Fix:
    """A proposed fix for the problem represented by a result object. A fix specifies a set of artifacts to modify. For each artifact, it specifies a set of bytes to remove, and provides a set of new bytes to replace them."""

    artifact_changes : list[ArtifactChange] = field(metadata={"schema_property_name": "artifactChanges"})
    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
