# This file was generated by jschema_to_python version 1.2.3.

from ._edge_traversal import EdgeTraversal
from ._message import Message
from ._multiformat_message_string import MultiformatMessageString
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class GraphTraversal:
    """Represents a path through a graph."""

    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    edge_traversals : list[EdgeTraversal] = field(factory=list, metadata={"schema_property_name": "edgeTraversals"})
    immutable_state : dict[str, MultiformatMessageString] = field(default=None, metadata={"schema_property_name": "immutableState"})
    initial_state : dict[str, MultiformatMessageString] = field(default=None, metadata={"schema_property_name": "initialState"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    result_graph_index : int = field(default=-1, metadata={"schema_property_name": "resultGraphIndex"})
    run_graph_index : int = field(default=-1, metadata={"schema_property_name": "runGraphIndex"})
