# This file was generated by jschema_to_python version 1.2.3.

from ._edge import Edge
from ._message import Message
from ._node import Node
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Graph:
    """A network of nodes and directed edges that describes some aspect of the structure of the code (for example, a call graph)."""

    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    edges : list[Edge] = field(factory=list, metadata={"schema_property_name": "edges"})
    nodes : list[Node] = field(factory=list, metadata={"schema_property_name": "nodes"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
