# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_location import ArtifactLocation
from ._configuration_override import ConfigurationOverride
from ._notification import Notification
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Invocation:
    """The runtime environment of the analysis tool run."""

    execution_successful : bool = field(metadata={"schema_property_name": "executionSuccessful"})
    account : str = field(default=None, metadata={"schema_property_name": "account"})
    arguments : list[str] = field(factory=list, metadata={"schema_property_name": "arguments"})
    command_line : str = field(default=None, metadata={"schema_property_name": "commandLine"})
    end_time_utc : str = field(default=None, metadata={"schema_property_name": "endTimeUtc"})
    environment_variables : dict[str, str] = field(default=None, metadata={"schema_property_name": "environmentVariables"})
    executable_location : ArtifactLocation = field(default=None, metadata={"schema_property_name": "executableLocation"})
    exit_code : int = field(default=None, metadata={"schema_property_name": "exitCode"})
    exit_code_description : str = field(default=None, metadata={"schema_property_name": "exitCodeDescription"})
    exit_signal_name : str = field(default=None, metadata={"schema_property_name": "exitSignalName"})
    exit_signal_number : int = field(default=None, metadata={"schema_property_name": "exitSignalNumber"})
    machine : str = field(default=None, metadata={"schema_property_name": "machine"})
    notification_configuration_overrides : list[ConfigurationOverride] = field(factory=list, metadata={"schema_property_name": "notificationConfigurationOverrides"})
    process_id : int = field(default=None, metadata={"schema_property_name": "processId"})
    process_start_failure_message : str = field(default=None, metadata={"schema_property_name": "processStartFailureMessage"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    response_files : list[ArtifactLocation] = field(factory=list, metadata={"schema_property_name": "responseFiles"})
    rule_configuration_overrides : list[ConfigurationOverride] = field(factory=list, metadata={"schema_property_name": "ruleConfigurationOverrides"})
    start_time_utc : str = field(default=None, metadata={"schema_property_name": "startTimeUtc"})
    stderr : ArtifactLocation = field(default=None, metadata={"schema_property_name": "stderr"})
    stdin : ArtifactLocation = field(default=None, metadata={"schema_property_name": "stdin"})
    stdout : ArtifactLocation = field(default=None, metadata={"schema_property_name": "stdout"})
    stdout_stderr : ArtifactLocation = field(default=None, metadata={"schema_property_name": "stdoutStderr"})
    tool_configuration_notifications : list[Notification] = field(factory=list, metadata={"schema_property_name": "toolConfigurationNotifications"})
    tool_execution_notifications : list[Notification] = field(factory=list, metadata={"schema_property_name": "toolExecutionNotifications"})
    working_directory : ArtifactLocation = field(default=None, metadata={"schema_property_name": "workingDirectory"})
