# This file was generated by jschema_to_python version 1.2.3.

from ._location_relationship import LocationRelationship
from ._logical_location import LogicalLocation
from ._message import Message
from ._physical_location import PhysicalLocation
from ._property_bag import PropertyBag
from ._region import Region
from attrs import define
from attrs import field


@define()
class Location:
    """A location within a programming artifact."""

    annotations : list[Region] = field(factory=list, metadata={"schema_property_name": "annotations"})
    id : int = field(default=-1, metadata={"schema_property_name": "id"})
    logical_locations : list[LogicalLocation] = field(factory=list, metadata={"schema_property_name": "logicalLocations"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    physical_location : PhysicalLocation = field(default=None, metadata={"schema_property_name": "physicalLocation"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    relationships : list[LocationRelationship] = field(factory=list, metadata={"schema_property_name": "relationships"})
