# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class LogicalLocation:
    """A logical location of a construct that produced a result."""

    decorated_name : str = field(default=None, metadata={"schema_property_name": "decoratedName"})
    fully_qualified_name : str = field(default=None, metadata={"schema_property_name": "fullyQualifiedName"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    kind : str = field(default=None, metadata={"schema_property_name": "kind"})
    name : str = field(default=None, metadata={"schema_property_name": "name"})
    parent_index : int = field(default=-1, metadata={"schema_property_name": "parentIndex"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
