# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Message:
    """Encapsulates a message intended to be read by the end user."""

    arguments : list[str] = field(factory=list, metadata={"schema_property_name": "arguments"})
    id : str = field(default=None, metadata={"schema_property_name": "id"})
    markdown : str = field(default=None, metadata={"schema_property_name": "markdown"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    text : str = field(default=None, metadata={"schema_property_name": "text"})
