# This file was generated by jschema_to_python version 1.2.3.

from ._location import Location
from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Node:
    """Represents a node in a graph."""

    id : str = field(metadata={"schema_property_name": "id"})
    children : list["Node"] = field(factory=list, metadata={"schema_property_name": "children"})
    label : Message = field(default=None, metadata={"schema_property_name": "label"})
    location : Location = field(default=None, metadata={"schema_property_name": "location"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
