# This file was generated by jschema_to_python version 1.2.3.

from ._address import Address
from ._artifact_location import ArtifactLocation
from ._property_bag import PropertyBag
from ._region import Region
from attrs import define
from attrs import field


@define()
class PhysicalLocation:
    """A physical location relevant to a result. Specifies a reference to a programming artifact together with a range of bytes or characters within that artifact."""

    address : Address = field(default=None, metadata={"schema_property_name": "address"})
    artifact_location : ArtifactLocation = field(default=None, metadata={"schema_property_name": "artifactLocation"})
    context_region : Region = field(default=None, metadata={"schema_property_name": "contextRegion"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    region : Region = field(default=None, metadata={"schema_property_name": "region"})
