# This file was generated by jschema_to_python version 1.2.3.

from attrs import define
from attrs import field


@define()
class PropertyBag:
    """Key/value pairs that provide additional information about the object."""

    tags : list[str] = field(factory=list, metadata={"schema_property_name": "tags"})
