# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Rectangle:
    """An area within an image."""

    bottom : float = field(default=None, metadata={"schema_property_name": "bottom"})
    left : float = field(default=None, metadata={"schema_property_name": "left"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    right : float = field(default=None, metadata={"schema_property_name": "right"})
    top : float = field(default=None, metadata={"schema_property_name": "top"})
