# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_content import ArtifactContent
from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class Region:
    """A region within an artifact where a result was detected."""

    byte_length : int = field(default=None, metadata={"schema_property_name": "byteLength"})
    byte_offset : int = field(default=-1, metadata={"schema_property_name": "byteOffset"})
    char_length : int = field(default=None, metadata={"schema_property_name": "charLength"})
    char_offset : int = field(default=-1, metadata={"schema_property_name": "charOffset"})
    end_column : int = field(default=None, metadata={"schema_property_name": "endColumn"})
    end_line : int = field(default=None, metadata={"schema_property_name": "endLine"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    snippet : ArtifactContent = field(default=None, metadata={"schema_property_name": "snippet"})
    source_language : str = field(default=None, metadata={"schema_property_name": "sourceLanguage"})
    start_column : int = field(default=None, metadata={"schema_property_name": "startColumn"})
    start_line : int = field(default=None, metadata={"schema_property_name": "startLine"})
