# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_content import ArtifactContent
from ._property_bag import PropertyBag
from ._region import Region
from attrs import define
from attrs import field


@define()
class Replacement:
    """The replacement of a single region of an artifact."""

    deleted_region : Region = field(metadata={"schema_property_name": "deletedRegion"})
    inserted_content : ArtifactContent = field(default=None, metadata={"schema_property_name": "insertedContent"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
