# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class ReportingConfiguration:
    """Information about a rule or notification that can be configured at runtime."""

    enabled : bool = field(default=True, metadata={"schema_property_name": "enabled"})
    level : str = field(default="warning", metadata={"schema_property_name": "level"})
    parameters : PropertyBag = field(default=None, metadata={"schema_property_name": "parameters"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    rank : float = field(default=-1.0, metadata={"schema_property_name": "rank"})
