# This file was generated by jschema_to_python version 1.2.3.

from ._multiformat_message_string import MultiformatMessageString
from ._property_bag import PropertyBag
from ._reporting_configuration import ReportingConfiguration
from ._reporting_descriptor_relationship import ReportingDescriptorRelationship
from attrs import define
from attrs import field


@define()
class ReportingDescriptor:
    """Metadata that describes a specific report produced by the tool, as part of the analysis it provides or its runtime reporting."""

    id : str = field(metadata={"schema_property_name": "id"})
    default_configuration : ReportingConfiguration = field(default=None, metadata={"schema_property_name": "defaultConfiguration"})
    deprecated_guids : list[str] = field(factory=list, metadata={"schema_property_name": "deprecatedGuids"})
    deprecated_ids : list[str] = field(factory=list, metadata={"schema_property_name": "deprecatedIds"})
    deprecated_names : list[str] = field(factory=list, metadata={"schema_property_name": "deprecatedNames"})
    full_description : MultiformatMessageString = field(default=None, metadata={"schema_property_name": "fullDescription"})
    guid : str = field(default=None, metadata={"schema_property_name": "guid"})
    help : MultiformatMessageString = field(default=None, metadata={"schema_property_name": "help"})
    help_uri : str = field(default=None, metadata={"schema_property_name": "helpUri"})
    message_strings : dict[str, MultiformatMessageString] = field(default=None, metadata={"schema_property_name": "messageStrings"})
    name : str = field(default=None, metadata={"schema_property_name": "name"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    relationships : list[ReportingDescriptorRelationship] = field(factory=list, metadata={"schema_property_name": "relationships"})
    short_description : MultiformatMessageString = field(default=None, metadata={"schema_property_name": "shortDescription"})
