# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from ._tool_component_reference import ToolComponentReference
from attrs import define
from attrs import field


@define()
class ReportingDescriptorReference:
    """Information about how to locate a relevant reporting descriptor."""

    guid : str = field(default=None, metadata={"schema_property_name": "guid"})
    id : str = field(default=None, metadata={"schema_property_name": "id"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    tool_component : ToolComponentReference = field(default=None, metadata={"schema_property_name": "toolComponent"})
