# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class RunAutomationDetails:
    """Information that describes a run's identity and role within an engineering system process."""

    correlation_guid : str = field(default=None, metadata={"schema_property_name": "correlationGuid"})
    description : Message = field(default=None, metadata={"schema_property_name": "description"})
    guid : str = field(default=None, metadata={"schema_property_name": "guid"})
    id : str = field(default=None, metadata={"schema_property_name": "id"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
