# This file was generated by jschema_to_python version 1.2.3.

from ._external_properties import ExternalProperties
from ._property_bag import PropertyBag
from ._run import Run
from attrs import define
from attrs import field


@define()
class SarifLog:
    """Static Analysis Results Format (SARIF) Version 2.1.0 JSON Schema: a standard format for the output of static analysis tools."""

    runs : list[Run] = field(metadata={"schema_property_name": "runs"})
    version : str = field(metadata={"schema_property_name": "version"})
    schema_uri : str = field(default=None, metadata={"schema_property_name": "$schema"})
    inline_external_properties : list[ExternalProperties] = field(factory=list, metadata={"schema_property_name": "inlineExternalProperties"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
