# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_location import ArtifactLocation
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class SpecialLocations:
    """Defines locations of special significance to SARIF consumers."""

    display_base : ArtifactLocation = field(default=None, metadata={"schema_property_name": "displayBase"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
