# This file was generated by jschema_to_python version 1.1.0.

import attr

@attr.s
class SpecialLocations(object):
    """Defines locations of special significance to SARIF consumers."""
    display_base = attr.ib(default=None)
    properties = attr.ib(default=None)
