# This file was generated by jschema_to_python version 1.2.3.

from ._location import Location
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class StackFrame:
    """A function call within a stack trace."""

    location : Location = field(default=None, metadata={"schema_property_name": "location"})
    module : str = field(default=None, metadata={"schema_property_name": "module"})
    parameters : list[str] = field(factory=list, metadata={"schema_property_name": "parameters"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    thread_id : int = field(default=None, metadata={"schema_property_name": "threadId"})
