# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._property_bag import PropertyBag
from ._stack_frame import StackFrame
from attrs import define
from attrs import field


@define()
class Stack:
    """A call stack that is relevant to a result."""

    frames : list[StackFrame] = field(metadata={"schema_property_name": "frames"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
