# This file was generated by jschema_to_python version 1.2.3.

from ._message import Message
from ._multiformat_message_string import MultiformatMessageString
from ._property_bag import PropertyBag
from ._thread_flow_location import ThreadFlowLocation
from attrs import define
from attrs import field


@define()
class ThreadFlow:
    """Describes a sequence of code locations that specify a path through a single thread of execution such as an operating system or fiber."""

    locations : list[ThreadFlowLocation] = field(metadata={"schema_property_name": "locations"})
    id : str = field(default=None, metadata={"schema_property_name": "id"})
    immutable_state : dict[str, MultiformatMessageString] = field(default=None, metadata={"schema_property_name": "immutableState"})
    initial_state : dict[str, MultiformatMessageString] = field(default=None, metadata={"schema_property_name": "initialState"})
    message : Message = field(default=None, metadata={"schema_property_name": "message"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
