# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from ._tool_component import ToolComponent
from attrs import define
from attrs import field


@define()
class Tool:
    """The analysis tool that was run."""

    driver : ToolComponent = field(metadata={"schema_property_name": "driver"})
    extensions : list[ToolComponent] = field(factory=list, metadata={"schema_property_name": "extensions"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
