# This file was generated by jschema_to_python version 1.2.3.

from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class ToolComponentReference:
    """Identifies a particular toolComponent object, either the driver or an extension."""

    guid : str = field(default=None, metadata={"schema_property_name": "guid"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    name : str = field(default=None, metadata={"schema_property_name": "name"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
