# This file was generated by jschema_to_python version 1.2.3.

from ._multiformat_message_string import MultiformatMessageString
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class TranslationMetadata:
    """Provides additional metadata related to translation."""

    name : str = field(metadata={"schema_property_name": "name"})
    download_uri : str = field(default=None, metadata={"schema_property_name": "downloadUri"})
    full_description : MultiformatMessageString = field(default=None, metadata={"schema_property_name": "fullDescription"})
    full_name : str = field(default=None, metadata={"schema_property_name": "fullName"})
    information_uri : str = field(default=None, metadata={"schema_property_name": "informationUri"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    short_description : MultiformatMessageString = field(default=None, metadata={"schema_property_name": "shortDescription"})
