# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_location import ArtifactLocation
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class VersionControlDetails:
    """Specifies the information necessary to retrieve a desired revision from a version control system."""

    repository_uri : str = field(metadata={"schema_property_name": "repositoryUri"})
    as_of_time_utc : str = field(default=None, metadata={"schema_property_name": "asOfTimeUtc"})
    branch : str = field(default=None, metadata={"schema_property_name": "branch"})
    mapped_to : ArtifactLocation = field(default=None, metadata={"schema_property_name": "mappedTo"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    revision_id : str = field(default=None, metadata={"schema_property_name": "revisionId"})
    revision_tag : str = field(default=None, metadata={"schema_property_name": "revisionTag"})
