# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_content import ArtifactContent
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class WebResponse:
    """Describes the response to an HTTP request."""

    body : ArtifactContent = field(default=None, metadata={"schema_property_name": "body"})
    headers : dict[str, str] = field(default=None, metadata={"schema_property_name": "headers"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    no_response_received : bool = field(default=False, metadata={"schema_property_name": "noResponseReceived"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    protocol : str = field(default=None, metadata={"schema_property_name": "protocol"})
    reason_phrase : str = field(default=None, metadata={"schema_property_name": "reasonPhrase"})
    status_code : int = field(default=None, metadata={"schema_property_name": "statusCode"})
    version : str = field(default=None, metadata={"schema_property_name": "version"})
