# This file was generated by jschema_to_python version 1.2.3.

from ._artifact_content import ArtifactContent
from ._property_bag import PropertyBag
from attrs import define
from attrs import field


@define()
class WebRequest:
    """Describes an HTTP request."""

    body : ArtifactContent = field(default=None, metadata={"schema_property_name": "body"})
    headers : dict[str, str] = field(default=None, metadata={"schema_property_name": "headers"})
    index : int = field(default=-1, metadata={"schema_property_name": "index"})
    method : str = field(default=None, metadata={"schema_property_name": "method"})
    parameters : dict[str, str] = field(default=None, metadata={"schema_property_name": "parameters"})
    properties : PropertyBag = field(default=None, metadata={"schema_property_name": "properties"})
    protocol : str = field(default=None, metadata={"schema_property_name": "protocol"})
    target : str = field(default=None, metadata={"schema_property_name": "target"})
    version : str = field(default=None, metadata={"schema_property_name": "version"})
