# This file was generated by jschema_to_python version 0.0.5.

class Artifact(object):
    """A single artifact. In some cases, this artifact might be nested within another artifact."""
    def __init__(self,
        contents=None,
        description=None,
        encoding=None,
        hashes=None,
        lastModifiedTimeUtc=None,
        length=-1,
        location=None,
        mimeType=None,
        offset=None,
        parentIndex=-1,
        properties=None,
        roles=[],
        sourceLanguage=None):

        self.contents=contents
        self.description=description
        self.encoding=encoding
        self.hashes=hashes
        self.lastModifiedTimeUtc=lastModifiedTimeUtc
        self.length=length
        self.location=location
        self.mimeType=mimeType
        self.offset=offset
        self.parentIndex=parentIndex
        self.properties=properties
        self.roles=roles
        self.sourceLanguage=sourceLanguage
