# This file was generated by jschema_to_python version 0.1.0.

class ArtifactContent(object):
    """Represents the contents of an artifact."""
    def __init__(self,
        binary=None,
        properties=None,
        rendered=None,
        text=None):

        self.binary=binary
        self.properties=properties
        self.rendered=rendered
        self.text=text
