# This file was generated by jschema_to_python version 0.0.5.

class ArtifactLocation(object):
    """Specifies the location of an artifact."""
    def __init__(self,
        description=None,
        index=-1,
        properties=None,
        uri=None,
        uriBaseId=None):

        self.description=description
        self.index=index
        self.properties=properties
        self.uri=uri
        self.uriBaseId=uriBaseId
