# This file was generated by jschema_to_python version 0.0.5.

class CodeFlow(object):
    """A set of threadFlows which together describe a pattern of code execution relevant to detecting a result."""
    def __init__(self,
        message=None,
        properties=None,
        threadFlows=None):

        missing_properties = []
        if threadFlows is None:
            missing_properties.append('threadFlows')
        if len(missing_properties) > 0:
            raise Exception('required properties of class CodeFlow were not provided: {}'.format(', '.join(missing_properties)))

        self.message=message
        self.properties=properties
        self.threadFlows=threadFlows
