# This file was generated by jschema_to_python version 0.1.0.

class ConfigurationOverride(object):
    """Information about how a specific rule or notification was reconfigured at runtime."""
    def __init__(self,
        configuration=None,
        descriptor=None,
        properties=None):

        missing_properties = []
        if configuration is None:
            missing_properties.append('configuration')
        if descriptor is None:
            missing_properties.append('descriptor')
        if len(missing_properties) > 0:
            raise Exception('required properties of class ConfigurationOverride were not provided: {}'.format(', '.join(missing_properties)))

        self.configuration=configuration
        self.descriptor=descriptor
        self.properties=properties
