# This file was generated by jschema_to_python version 0.1.0.

class Conversion(object):
    """Describes how a converter transformed the output of a static analysis tool from the analysis tool's native output format into the SARIF format."""
    def __init__(self,
        analysisToolLogFiles=[],
        invocation=None,
        properties=None,
        tool=None):

        missing_properties = []
        if tool is None:
            missing_properties.append('tool')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Conversion were not provided: {}'.format(', '.join(missing_properties)))

        self.analysisToolLogFiles=analysisToolLogFiles
        self.invocation=invocation
        self.properties=properties
        self.tool=tool
