# This file was generated by jschema_to_python version 0.1.0.

class EdgeTraversal(object):
    """Represents the traversal of a single edge during a graph traversal."""
    def __init__(self,
        edgeId=None,
        finalState=None,
        message=None,
        properties=None,
        stepOverEdgeCount=None):

        missing_properties = []
        if edgeId is None:
            missing_properties.append('edgeId')
        if len(missing_properties) > 0:
            raise Exception('required properties of class EdgeTraversal were not provided: {}'.format(', '.join(missing_properties)))

        self.edgeId=edgeId
        self.finalState=finalState
        self.message=message
        self.properties=properties
        self.stepOverEdgeCount=stepOverEdgeCount
