# This file was generated by jschema_to_python version 0.1.0.

class Exception(object):
    """Describes a runtime exception encountered during the execution of an analysis tool."""
    def __init__(self,
        innerExceptions=[],
        kind=None,
        message=None,
        properties=None,
        stack=None):

        self.innerExceptions=innerExceptions
        self.kind=kind
        self.message=message
        self.properties=properties
        self.stack=stack
