# This file was generated by jschema_to_python version 0.1.0.

class ExternalProperties(object):
    """The top-level element of an external property file."""
    def __init__(self,
        addresses=[],
        artifacts=None,
        conversion=None,
        driver=None,
        extensions=[],
        externalizedProperties=None,
        graphs=[],
        guid=None,
        invocations=[],
        logicalLocations=[],
        policies=[],
        properties=None,
        results=[],
        runGuid=None,
        schema=None,
        taxonomies=[],
        threadFlowLocations=[],
        translations=[],
        version=None,
        webRequests=[],
        webResponses=[]):

        self.addresses=addresses
        self.artifacts=artifacts
        self.conversion=conversion
        self.driver=driver
        self.extensions=extensions
        self.externalizedProperties=externalizedProperties
        self.graphs=graphs
        self.guid=guid
        self.invocations=invocations
        self.logicalLocations=logicalLocations
        self.policies=policies
        self.properties=properties
        self.results=results
        self.runGuid=runGuid
        self.schema=schema
        self.taxonomies=taxonomies
        self.threadFlowLocations=threadFlowLocations
        self.translations=translations
        self.version=version
        self.webRequests=webRequests
        self.webResponses=webResponses
