# This file was generated by jschema_to_python version 0.0.5.

class Fix(object):
    """A proposed fix for the problem represented by a result object. A fix specifies a set of artifacts to modify. For each artifact, it specifies a set of bytes to remove, and provides a set of new bytes to replace them."""
    def __init__(self,
        artifactChanges=None,
        description=None,
        properties=None):

        missing_properties = []
        if artifactChanges is None:
            missing_properties.append('artifactChanges')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Fix were not provided: {}'.format(', '.join(missing_properties)))

        self.artifactChanges=artifactChanges
        self.description=description
        self.properties=properties
