# This file was generated by jschema_to_python version 0.1.0.

class GraphTraversal(object):
    """Represents a path through a graph."""
    def __init__(self,
        description=None,
        edgeTraversals=[],
        immutableState=None,
        initialState=None,
        properties=None,
        resultGraphIndex=-1,
        runGraphIndex=-1):

        self.description=description
        self.edgeTraversals=edgeTraversals
        self.immutableState=immutableState
        self.initialState=initialState
        self.properties=properties
        self.resultGraphIndex=resultGraphIndex
        self.runGraphIndex=runGraphIndex
