# This file was generated by jschema_to_python version 0.0.5.

class Graph(object):
    """A network of nodes and directed edges that describes some aspect of the structure of the code (for example, a call graph)."""
    def __init__(self,
        description=None,
        edges=[],
        nodes=[],
        properties=None):

        self.description=description
        self.edges=edges
        self.nodes=nodes
        self.properties=properties
