# This file was generated by jschema_to_python version 0.0.5.

class Invocation(object):
    """The runtime environment of the analysis tool run."""
    def __init__(self,
        account=None,
        arguments=None,
        commandLine=None,
        endTimeUtc=None,
        environmentVariables=None,
        executableLocation=None,
        executionSuccessful=None,
        exitCode=None,
        exitCodeDescription=None,
        exitSignalName=None,
        exitSignalNumber=None,
        machine=None,
        notificationConfigurationOverrides=[],
        processId=None,
        processStartFailureMessage=None,
        properties=None,
        responseFiles=None,
        ruleConfigurationOverrides=[],
        startTimeUtc=None,
        stderr=None,
        stdin=None,
        stdout=None,
        stdoutStderr=None,
        toolConfigurationNotifications=[],
        toolExecutionNotifications=[],
        workingDirectory=None):

        missing_properties = []
        if executionSuccessful is None:
            missing_properties.append('executionSuccessful')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Invocation were not provided: {}'.format(', '.join(missing_properties)))

        self.account=account
        self.arguments=arguments
        self.commandLine=commandLine
        self.endTimeUtc=endTimeUtc
        self.environmentVariables=environmentVariables
        self.executableLocation=executableLocation
        self.executionSuccessful=executionSuccessful
        self.exitCode=exitCode
        self.exitCodeDescription=exitCodeDescription
        self.exitSignalName=exitSignalName
        self.exitSignalNumber=exitSignalNumber
        self.machine=machine
        self.notificationConfigurationOverrides=notificationConfigurationOverrides
        self.processId=processId
        self.processStartFailureMessage=processStartFailureMessage
        self.properties=properties
        self.responseFiles=responseFiles
        self.ruleConfigurationOverrides=ruleConfigurationOverrides
        self.startTimeUtc=startTimeUtc
        self.stderr=stderr
        self.stdin=stdin
        self.stdout=stdout
        self.stdoutStderr=stdoutStderr
        self.toolConfigurationNotifications=toolConfigurationNotifications
        self.toolExecutionNotifications=toolExecutionNotifications
        self.workingDirectory=workingDirectory
