# This file was generated by jschema_to_python version 0.1.0.

class Location(object):
    """A location within a programming artifact."""
    def __init__(self,
        annotations=[],
        id=-1,
        logicalLocations=[],
        message=None,
        physicalLocation=None,
        properties=None,
        relationships=[]):

        self.annotations=annotations
        self.id=id
        self.logicalLocations=logicalLocations
        self.message=message
        self.physicalLocation=physicalLocation
        self.properties=properties
        self.relationships=relationships
