# This file was generated by jschema_to_python version 0.0.5.

class LogicalLocation(object):
    """A logical location of a construct that produced a result."""
    def __init__(self,
        decoratedName=None,
        fullyQualifiedName=None,
        index=-1,
        kind=None,
        name=None,
        parentIndex=-1,
        properties=None):

        self.decoratedName=decoratedName
        self.fullyQualifiedName=fullyQualifiedName
        self.index=index
        self.kind=kind
        self.name=name
        self.parentIndex=parentIndex
        self.properties=properties
