# This file was generated by jschema_to_python version 0.1.0.

class Message(object):
    """Encapsulates a message intended to be read by the end user."""
    def __init__(self,
        arguments=[],
        id=None,
        markdown=None,
        properties=None,
        text=None):

        self.arguments=arguments
        self.id=id
        self.markdown=markdown
        self.properties=properties
        self.text=text
