# This file was generated by jschema_to_python version 0.0.5.

class Node(object):
    """Represents a node in a graph."""
    def __init__(self,
        children=[],
        id=None,
        label=None,
        location=None,
        properties=None):

        missing_properties = []
        if id is None:
            missing_properties.append('id')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Node were not provided: {}'.format(', '.join(missing_properties)))

        self.children=children
        self.id=id
        self.label=label
        self.location=location
        self.properties=properties
