# This file was generated by jschema_to_python version 0.1.0.

class PhysicalLocation(object):
    """A physical location relevant to a result. Specifies a reference to a programming artifact together with a range of bytes or characters within that artifact."""
    def __init__(self,
        address=None,
        artifactLocation=None,
        contextRegion=None,
        properties=None,
        region=None):

        self.address=address
        self.artifactLocation=artifactLocation
        self.contextRegion=contextRegion
        self.properties=properties
        self.region=region
