# This file was generated by jschema_to_python version 0.0.5.

class PropertyBag(object):
    """Key/value pairs that provide additional information about the object."""
    def __init__(self,
        tags=[]):

        self.tags=tags
