# This file was generated by jschema_to_python version 0.0.5.

class Rectangle(object):
    """An area within an image."""
    def __init__(self,
        bottom=None,
        left=None,
        message=None,
        properties=None,
        right=None,
        top=None):

        self.bottom=bottom
        self.left=left
        self.message=message
        self.properties=properties
        self.right=right
        self.top=top
