# This file was generated by jschema_to_python version 0.1.0.

class Replacement(object):
    """The replacement of a single region of an artifact."""
    def __init__(self,
        deletedRegion=None,
        insertedContent=None,
        properties=None):

        missing_properties = []
        if deletedRegion is None:
            missing_properties.append('deletedRegion')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Replacement were not provided: {}'.format(', '.join(missing_properties)))

        self.deletedRegion=deletedRegion
        self.insertedContent=insertedContent
        self.properties=properties
