# This file was generated by jschema_to_python version 0.1.0.

class ReportingDescriptor(object):
    """Metadata that describes a specific report produced by the tool, as part of the analysis it provides or its runtime reporting."""
    def __init__(self,
        defaultConfiguration=None,
        deprecatedGuids=None,
        deprecatedIds=None,
        deprecatedNames=None,
        fullDescription=None,
        guid=None,
        help=None,
        helpUri=None,
        id=None,
        messageStrings=None,
        name=None,
        properties=None,
        relationships=[],
        shortDescription=None):

        missing_properties = []
        if id is None:
            missing_properties.append('id')
        if len(missing_properties) > 0:
            raise Exception('required properties of class ReportingDescriptor were not provided: {}'.format(', '.join(missing_properties)))

        self.defaultConfiguration=defaultConfiguration
        self.deprecatedGuids=deprecatedGuids
        self.deprecatedIds=deprecatedIds
        self.deprecatedNames=deprecatedNames
        self.fullDescription=fullDescription
        self.guid=guid
        self.help=help
        self.helpUri=helpUri
        self.id=id
        self.messageStrings=messageStrings
        self.name=name
        self.properties=properties
        self.relationships=relationships
        self.shortDescription=shortDescription
