# This file was generated by jschema_to_python version 0.0.5.

class ReportingConfiguration(object):
    """Information about a rule or notification that can be configured at runtime."""
    def __init__(self,
        enabled=True,
        level=warning,
        parameters=None,
        properties=None,
        rank=-1.0):

        self.enabled=enabled
        self.level=level
        self.parameters=parameters
        self.properties=properties
        self.rank=rank
