# This file was generated by jschema_to_python version 0.1.0.

class ReportingDescriptorReference(object):
    """Information about how to locate a relevant reporting descriptor."""
    def __init__(self,
        guid=None,
        id=None,
        index=-1,
        properties=None,
        toolComponent=None):

        self.guid=guid
        self.id=id
        self.index=index
        self.properties=properties
        self.toolComponent=toolComponent
