# This file was generated by jschema_to_python version 0.1.0.

class Run(object):
    """Describes a single run of an analysis tool, and contains the reported output of that run."""
    def __init__(self,
        addresses=[],
        artifacts=None,
        automationDetails=None,
        baselineGuid=None,
        columnKind=None,
        conversion=None,
        defaultEncoding=None,
        defaultSourceLanguage=None,
        externalPropertyFileReferences=None,
        graphs=[],
        invocations=[],
        language='en-US',
        logicalLocations=[],
        newlineSequences=['\r\n', '\n'],
        originalUriBaseIds=None,
        policies=[],
        properties=None,
        redactionTokens=[],
        results=None,
        runAggregates=[],
        specialLocations=None,
        taxonomies=[],
        threadFlowLocations=[],
        tool=None,
        translations=[],
        versionControlProvenance=[],
        webRequests=[],
        webResponses=[]):

        missing_properties = []
        if tool is None:
            missing_properties.append('tool')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Run were not provided: {}'.format(', '.join(missing_properties)))

        self.addresses=addresses
        self.artifacts=artifacts
        self.automationDetails=automationDetails
        self.baselineGuid=baselineGuid
        self.columnKind=columnKind
        self.conversion=conversion
        self.defaultEncoding=defaultEncoding
        self.defaultSourceLanguage=defaultSourceLanguage
        self.externalPropertyFileReferences=externalPropertyFileReferences
        self.graphs=graphs
        self.invocations=invocations
        self.language=language
        self.logicalLocations=logicalLocations
        self.newlineSequences=newlineSequences
        self.originalUriBaseIds=originalUriBaseIds
        self.policies=policies
        self.properties=properties
        self.redactionTokens=redactionTokens
        self.results=results
        self.runAggregates=runAggregates
        self.specialLocations=specialLocations
        self.taxonomies=taxonomies
        self.threadFlowLocations=threadFlowLocations
        self.tool=tool
        self.translations=translations
        self.versionControlProvenance=versionControlProvenance
        self.webRequests=webRequests
        self.webResponses=webResponses
