# This file was generated by jschema_to_python version 0.0.5.

class RunAutomationDetails(object):
    """Information that describes a run's identity and role within an engineering system process."""
    def __init__(self,
        correlationGuid=None,
        description=None,
        guid=None,
        id=None,
        properties=None):

        self.correlationGuid=correlationGuid
        self.description=description
        self.guid=guid
        self.id=id
        self.properties=properties
