# This file was generated by jschema_to_python version 0.0.5.

class SpecialLocations(object):
    """Defines locations of special significance to SARIF consumers."""
    def __init__(self,
        displayBase=None,
        properties=None):

        self.displayBase=displayBase
        self.properties=properties
