# This file was generated by jschema_to_python version 0.0.5.

class StackFrame(object):
    """A function call within a stack trace."""
    def __init__(self,
        location=None,
        module=None,
        parameters=[],
        properties=None,
        threadId=None):

        self.location=location
        self.module=module
        self.parameters=parameters
        self.properties=properties
        self.threadId=threadId
