# This file was generated by jschema_to_python version 0.0.5.

class Suppression(object):
    """A suppression that is relevant to a result."""
    def __init__(self,
        guid=None,
        justification=None,
        kind=None,
        location=None,
        properties=None,
        state=None):

        missing_properties = []
        if kind is None:
            missing_properties.append('kind')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Suppression were not provided: {}'.format(', '.join(missing_properties)))

        self.guid=guid
        self.justification=justification
        self.kind=kind
        self.location=location
        self.properties=properties
        self.state=state
