# This file was generated by jschema_to_python version 0.1.0.

class ThreadFlowLocation(object):
    """A location visited by an analysis tool while simulating or monitoring the execution of a program."""
    def __init__(self,
        executionOrder=-1,
        executionTimeUtc=None,
        importance='important',
        index=-1,
        kinds=[],
        location=None,
        module=None,
        nestingLevel=None,
        properties=None,
        stack=None,
        state=None,
        taxa=[],
        webRequest=None,
        webResponse=None):

        self.executionOrder=executionOrder
        self.executionTimeUtc=executionTimeUtc
        self.importance=importance
        self.index=index
        self.kinds=kinds
        self.location=location
        self.module=module
        self.nestingLevel=nestingLevel
        self.properties=properties
        self.stack=stack
        self.state=state
        self.taxa=taxa
        self.webRequest=webRequest
        self.webResponse=webResponse
