# This file was generated by jschema_to_python version 0.0.5.

class Tool(object):
    """The analysis tool that was run."""
    def __init__(self,
        driver=None,
        extensions=[],
        properties=None):

        missing_properties = []
        if driver is None:
            missing_properties.append('driver')
        if len(missing_properties) > 0:
            raise Exception('required properties of class Tool were not provided: {}'.format(', '.join(missing_properties)))

        self.driver=driver
        self.extensions=extensions
        self.properties=properties
