# This file was generated by jschema_to_python version 0.1.0.

class ToolComponentReference(object):
    """Identifies a particular toolComponent object, either the driver or an extension."""
    def __init__(self,
        guid=None,
        index=-1,
        name=None,
        properties=None):

        self.guid=guid
        self.index=index
        self.name=name
        self.properties=properties
