# This file was generated by jschema_to_python version 0.0.5.

class TranslationMetadata(object):
    """Provides additional metadata related to translation."""
    def __init__(self,
        downloadUri=None,
        fullDescription=None,
        fullName=None,
        informationUri=None,
        name=None,
        properties=None,
        shortDescription=None):

        missing_properties = []
        if name is None:
            missing_properties.append('name')
        if len(missing_properties) > 0:
            raise Exception('required properties of class TranslationMetadata were not provided: {}'.format(', '.join(missing_properties)))

        self.downloadUri=downloadUri
        self.fullDescription=fullDescription
        self.fullName=fullName
        self.informationUri=informationUri
        self.name=name
        self.properties=properties
        self.shortDescription=shortDescription
