# This file was generated by jschema_to_python version 0.1.0.

class VersionControlDetails(object):
    """Specifies the information necessary to retrieve a desired revision from a version control system."""
    def __init__(self,
        asOfTimeUtc=None,
        branch=None,
        mappedTo=None,
        properties=None,
        repositoryUri=None,
        revisionId=None,
        revisionTag=None):

        missing_properties = []
        if repositoryUri is None:
            missing_properties.append('repositoryUri')
        if len(missing_properties) > 0:
            raise Exception('required properties of class VersionControlDetails were not provided: {}'.format(', '.join(missing_properties)))

        self.asOfTimeUtc=asOfTimeUtc
        self.branch=branch
        self.mappedTo=mappedTo
        self.properties=properties
        self.repositoryUri=repositoryUri
        self.revisionId=revisionId
        self.revisionTag=revisionTag
