# This file was generated by jschema_to_python version 0.0.5.

class WebRequest(object):
    """Describes an HTTP request."""
    def __init__(self,
        body=None,
        headers=None,
        index=-1,
        method=None,
        parameters=None,
        properties=None,
        protocol=None,
        target=None,
        version=None):

        self.body=body
        self.headers=headers
        self.index=index
        self.method=method
        self.parameters=parameters
        self.properties=properties
        self.protocol=protocol
        self.target=target
        self.version=version
