# This file was generated by jschema_to_python version 0.0.5.

class WebResponse(object):
    """Describes the response to an HTTP request."""
    def __init__(self,
        body=None,
        headers=None,
        index=-1,
        noResponseReceived=False,
        properties=None,
        protocol=None,
        reasonPhrase=None,
        statusCode=None,
        version=None):

        self.body=body
        self.headers=headers
        self.index=index
        self.noResponseReceived=noResponseReceived
        self.properties=properties
        self.protocol=protocol
        self.reasonPhrase=reasonPhrase
        self.statusCode=statusCode
        self.version=version
